### ISSUE TITLE
src/call.cpp:198:22: error: 'stoi' is not a member of 'std'` 

### ISSUE THREAD

**Issue by wdoekes** [SIPp/sipp#219]
I'm told it fails to compile on ubuntu 12.04 because of the above error. 12.04 ships with 4.6.3-1ubuntu5 I think.

This would probably have been cought by travis if I hadn't updated it to use dist:trusty.
