### ISSUE TITLE
Cant compile on MAC OS X 10.9.4

### ISSUE THREAD

**Issue by dmpanch** [SIPp/sipp#81]
g++ -DHAVE_CONFIG_H  -DPCAPPLAY -DRTP_STREAM    -I. -I./include  -I./include -D__DARWIN   -g -O2 -MT src/sipp-time.o -MD -MP -MF src/.deps/sipp-time.Tpo -c -o src/sipp-time.o `test -f 'src/time.cpp' || echo './'`src/time.cpp
src/time.cpp:59:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    clock_gettime(CLOCK_MONOTONIC, &time);
                  ^
1 error generated.
make: **\* [src/sipp-time.o] Error 1
